### ISSUE TITLE
wanna try to use ToooMail

### ISSUE THREAD

**Issue by istek** [MattiaFailla/ToooMail#101]
Hi,
i didn't find any download link at your official website.

how to download the installer?

thanks.

**Comment by MattiaFailla** [comment]
Hello, thank you for your interest in this project!

Currently the application is under heavy development and we aren't ready for a release yet.

If you are really willing to try the application I can write here some quick instructions on how to download and start the project.

**Comment by istek** [comment]
Hi,
If you can write some instructions , that's really good.
Thanks.

**Comment by MattiaFailla** [comment]
Hello! 
I've prepared a wiki page: https://github.com/MattiaFailla/ToooMail/wiki

If you encounter any problem or something is unclear please let me know and i will fix the wiki. During the day I will try to deepen how the application architecture works in the wiki.
