### ISSUE TITLE
Search in db for keywords

### ISSUE THREAD

**Issue by MattiaFailla** [MattiaFailla/ToooMail#62]
We should add func to search in the db for a given keyword.

**Comment by MattiaFailla** [comment]
Serch in: 

- email title
- email sender name
- email date
- email tag
- email comment
- email filename

**Comment by nocturn9x** [comment]
Something similar to a `LIKE` query?

**Comment by MattiaFailla** [comment]
Locating https://www.sqlite.org/fts5.html (thanks to @basic-ph)

**Comment by basic-ph** [comment]
> Locating https://stackoverflow.com/a/54118033 (thanks to @basic-ph)

Maybe you mean this: https://www.sqlite.org/fts5.html

**Comment by MattiaFailla** [comment]
Adding `search_mail` in db_api 
Adding `search_mail` in imap_api
