### ISSUE TITLE
Add tags to the email 

### ISSUE THREAD

**Issue by MattiaFailla** [MattiaFailla/ToooMail#70]
![image](https://user-images.githubusercontent.com/11872425/75933668-d7564e00-5e7a-11ea-9217-7ec7704ec1b6.png)

Based on the title or sender name

**Comment by MattiaFailla** [comment]
![image0](https://user-images.githubusercontent.com/11872425/80868023-2a405c00-8c98-11ea-8925-6526aff28bb5.jpg)

**Comment by basic-ph** [comment]
`get_tags` (ok)
`create_tag` (check this)
`set_tag` (todo)
...the best is yet to come...
